config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  devise_for :users
  root to: 'sites#index'

  resources :sites do
    resource :sitemap_file, only: :show, shallow: true 
  end

  get :robot, to: 'robots#robot', as: :robot_txt
  get :parsing_page, to: 'parsing_pages#parsing_page'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
  belongs_to :sitemap_file

  def to_s
    url
  end

  def parser
    WebPageParser::PageParser.new(url)
  end
end

app/models/site.rb
class Site < ApplicationRecord
  belongs_to :user
  has_one :sitemap_file, dependent: :destroy

  validates :domain, presence: true, uniqueness: { case_sensitive: false }
  validates :user, presence: true

  after_create :parse_sitemap_job

  def sitemap
    sparser = SitemapParser.new(domain)
    create_sitemap_file(path: sparser.sitemap_path)
  end

  def save_urls
    sparser = SitemapParser.new(domain)
    urls = sparser.urls
    urls.each do |url|
      sitemap_file.pages.create(url: url)
    end
  end

  private

  def parse_sitemap_job
    ParseSitemapJob.perform_later(self)
  end
end

app/models/sitemap_file.rb
class SitemapFile < ApplicationRecord
  belongs_to :site
  has_many :pages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :sites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/parsing_pages_controller.rb
class ParsingPagesController < ApplicationController
  def parsing_page
    @page = Page.find(params[:id])
    @parser = @page.parser
  end
end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  def robot
    @site = Site.find(params[:site_id])
    @robots = RobotsTxt.new(@site.domain).read
    if @robots
      render plain: @robots
    else
      render plain: 'File robots.txt was not found!'
    end
  end
end

app/controllers/sitemap_files_controller.rb
class SitemapFilesController < ApplicationController
  before_action :find_site

  def show
    @sitemap_file = @site.sitemap_file
  end

  private

  def find_site
    @site = Site.find(params[:site_id])
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.order(created_at: :desc).limit(10)
  end

  def new
    @site = Site.new
  end

  def create
    @site = current_user.sites.new(params.require(:site).permit(:domain))
    if @site.save
      redirect_to sites_path, notice: t('.domain_added')
    else
      redirect_to sites_path
    end
  end

  def show
    @site = Site.find(params[:id])
    @checkdomain = CheckDomain.new(@site.domain)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def count_pages(site)
    site.sitemap_file.pages.count
  rescue
    0
  end

  def format_date(date, options = { time: true })
    format = options[:time] ? '%d-%m-%Y %H:%M' : '%d.%m.%Y'
    date&.strftime(format)
  end
  def truncate(string, max)
    string.length > max ? "#{string[0...max]}..." : string
  end
end

app/helpers/parsing_pages_helper.rb
module ParsingPagesHelper
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/helpers/sitemap_files_helper.rb
module SitemapFilesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="utf-8"]
    title
      | SEO | HOME
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render partial: 'shared/navbar'  
    .container
      #flash_messages
        = flash_messages(:close)
      = yield

app/views/parsing_pages/parsing_page.html.slim
br
.text-center
  p= link_to @page.url, @page.url, target: :_blank

- unless @parser.nil?
p 
  |  
  b titel:  
  = @parser.title
  br 
  |  
  b charset:   
  = @parser.charset
  br
  |  
  b X-UA-Compatible:   
  = @parser.compatible
  br
  |  
  b viewport:   
  = @parser.compatible       
  br
  |  
  b description:   
  = @parser.description
  br
  |  
  b lang:   
  = @parser.language
  br
  |  
  b keywords:  
  = @parser.keywords 
  br
  |  
  b tag h1 headlines:  
  = @parser.tag_h_one

b Теги и количество
p 
  - @parser.count_tags.each do |tag, count|
        = tag
        |:  
        b = count
        br

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">SEO-Анализ</a>
      <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.email, edit_user_registration_path, class: 'btn btn-light'%>
          </li>
          <li class="nav-item">
            <%= link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-light' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Регистрация', new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
</nav>

app/views/sitemap_files/_page_sitemap_file.html.slim
tr
  td = link_to (truncate page.url, 100), url_for(page.url), target: :_blank
  td = link_to t('.parse'), parsing_page_path(id: page.id), target: :_blank

app/views/sitemap_files/show.html.slim
br
  .text-center
    - if @sitemap_file
      | Sitemap файл найден
      |  
      b = @sitemap_file&.path

table.table.table-striped
  tbody
    - if @sitemap_file
        = render partial: 'sitemap_files/page_sitemap_file',  collection: @list_pages = @sitemap_file.pages.reverse.paginate(:page => params[:page], :per_page => 20), as: :page

- unless @list_pages.nil?
  = will_paginate(@list_pages, renderer: WillPaginate::ActionView::BootstrapLinkRenderer)

app/views/sites/_form.html.slim
.col-md-4.offset-md-4
  = simple_form_for Site.new do |f|
    = f.input :domain
    = f.submit t('.create'), class: "btn btn-outline-secondary"

app/views/sites/_site.html.slim
tr
  td = site.domain
  td = link_to t('.open'), "http://#{site.domain}", target: :blank
  td = link_to t('.run_test'), site_path(site)
  td = link_to t('.list_pages'), site_sitemap_file_path(site) 
  td = count_pages(site)
  td = link_to 'robots.txt', robot_txt_path(site_id: site.id), target: :_blank
  td = format_date(site.created_at, time: true)

    

app/views/sites/index.html.slim
p 
  h4.text-center = t('.list_domain')
  .text-right
    = link_to t('.add'), new_site_path

.sites
  table.table.borderless.text-left
    thead.thead-dark
      tr
        th = t('.domain')
        th = t('.link')
        th = t('.test')
        th = t('.url_links')
        th = t('.count_pages')
        th = t('.file_robots')
        th = t('.date')
    tbody
      = render @sites

app/views/sites/new.html.slim
= render 'form'

app/views/sites/show.html.slim
br
.text-left
  = link_to t('.back'), sites_path

p.text-center
  b =@site.domain
table.table.borderless.text-left
  thead.thead-light
    tr
      th url
      th = t('.protocol')
      th = t('.port')
      th = t('.code')
      th = t('.message')
  tbody
    tr
      td = @checkdomain.uri_http
      td = @checkdomain.uri_http.scheme
      td = @checkdomain.uri_http.port
      td = @checkdomain.code(@checkdomain.uri_http)
      td = @checkdomain.message(@checkdomain.uri_http)
    tr
      td = @checkdomain.uri_https
      td = @checkdomain.uri_https.scheme
      td = @checkdomain.uri_https.port
      td = @checkdomain.code(@checkdomain.uri_https)
      td = @checkdomain.message(@checkdomain.uri_https)
    tr
      td = @checkdomain.uri_http_www
      td = @checkdomain.uri_http_www.scheme
      td = @checkdomain.uri_http_www.port
      td = @checkdomain.code(@checkdomain.uri_http_www)
      td = @checkdomain.message(@checkdomain.uri_http_www)
    tr
      td = @checkdomain.uri_https_www
      td = @checkdomain.uri_https_www.scheme
      td = @checkdomain.uri_https_www.port
      td = @checkdomain.code(@checkdomain.uri_https_www)
      td = @checkdomain.message(@checkdomain.uri_https_www)

- if @checkdomain.code(@checkdomain.uri_http)
    p
      .card
        .card-header.text-center
          = t('.detail')
          |  
          = @checkdomain.uri_http
        .card-body
          p
            -@checkdomain.request(@checkdomain.uri_http)&.each_header do |key, value|
                  =key 
                  |    =>  
                  =value
                  br

- if @checkdomain.code(@checkdomain.uri_https)
    p
      .card
        .card-header.text-center
          = t('.detail')
          |  
          = @checkdomain.uri_https
        .card-body
          p
            -@checkdomain.request(@checkdomain.uri_https)&.each_header do |key, value|
                  =key 
                  |    =>  
                  =value
                  br  

- if @checkdomain.code(@checkdomain.uri_http_www)
  p
    .card
      .card-header.text-center
        = t('.detail')
        |    
        = @checkdomain.uri_http_www
      .card-body
        p
          -@checkdomain.request(@checkdomain.uri_http_www)&.each_header do |key, value|
                =key 
                |    =>  
                =value
                br    

- if @checkdomain.code(@checkdomain.uri_https_www)
  p
    .card
      .card-header.text-center
        = t('.detail')
        |  
        = @checkdomain.uri_https_www
      .card-body
        p
          -@checkdomain.request(@checkdomain.uri_https_www)&.each_header do |key, value|
                =key 
                |    =>  
                =value
                br  